[phases.setup]
nixPkgs = ["nodejs_22", "python312", "python312Packages.pip"]

[phases.install]
cmds = ["pnpm install", "pip install requests flask mysql-connector-python"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
